version: '3.8'

services:

  app:
    build:
      context: .
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/os_zalik_db
      SPRING_DATASOURCE_USERNAME: "my_user"
      SPRING_DATASOURCE_PASSWORD: "password"
    ports:
     - 8080:8080
